export default types = {
    //general
    RECEIVE_STANDARD_ERROR: 'RECEIVE_STANDARD_ERROR',
  
    //user
    REQUEST_USER_SUCCESS: 'REQUEST_USER_SUCCESS',
    REQUEST_USER: 'REQUEST_USER',
    LOGOUT: 'LOGOUT',
  }